---
# wzrd.yml
# Ubuntu 12.04 required due to a bug with fastcgi in 14.04
-
  hosts: appserver
  remote_user: ubuntu
  sudo: yes
  roles:
    - ami
    - nginx
    - services
    - startup
    - production
