---
# configure for production

- name: ensure pre-existing repo is removed
  file: path={{app_base_path}} state=absent

- name: clone git repo
  git: dest={{app_base_path}} repo={{git_repo}}

- name: npm install
  npm: path={{app_base_path}}

- name: make sure a project config directory exists
  file: path={{app_base_path}}/config state=directory
