---
# configure nginx

- name: make sure nginx has a configuration file
  template: src=wzrd.conf dest=/etc/nginx/conf.d/wzrd.conf backup=no

- name: restart nginx
  service: name=nginx state=restarted

- name: Make sure package.json is on the box
  copy: src=../../package.json dest={{app_base_path}} backup=no

- name: Make sure NPM install has been run
  npm: path={{app_base_path}}
